apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: {{ .Values.azureidentitylabels }}
  namespace: {{ .Values.namespace }}
spec:
  clientID: {{ .Values.azureidentityClientID }}
  resourceID: {{ .Values.azureidentityResourceID }}