kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gpsdev-admin-rlbnd
  namespace: gps-aks-dev
  labels:
    fnf_app_id1: "17"
    fnf_app_name: "GlobalPremierServices"
    fnf_businessservice_id: "17.DEV"
    fnf_costcenter: "01400.901302.160"
    fnf_datacenter: "Azure"
    fnf_lineofbusiness_id: "1"
    fnf_parenthosting_id: "2.1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gps-dev-admin-rl
  #name: gps-aks-nonprd
subjects:
  - kind: Group
  #namespace: cnst-aks-dev
    name: c36134e5-fe66-42c8-9013-8cefffcd5c9f

  - kind: User
  #namespace: cnst-aks-dev
    name: da1684dc-1fa4-4fc1-9e5e-28e2cc62a0cb
